run:
  tests: true
linters:
  enable-all: true
  disable:
    - dupl
    - cyclop
    - exhaustivestruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - goerr113
    - gomnd
    - lll
    - maligned
    - paralleltest
    - testpackage
    - wrapcheck
    - wsl
