apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduled-pod-autoscaler
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: scheduled-pod-autoscaler
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scheduled-pod-autoscaler
    spec:
      containers:
        - command:
            - /manager
          args:
            - --enable-leader-election
          image: controller:latest
          name: manager
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
      terminationGracePeriodSeconds: 10
