# permissions for end users to edit scheduledpodautoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scheduledpodautoscaler-editor-role
rules:
- apiGroups:
  - autoscaling.d-kuro.github.io
  resources:
  - scheduledpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.d-kuro.github.io
  resources:
  - scheduledpodautoscalers/status
  verbs:
  - get
