# permissions for end users to view schedules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: schedule-viewer-role
rules:
- apiGroups:
  - autoscaling.d-kuro.github.io
  resources:
  - schedules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling.d-kuro.github.io
  resources:
  - schedules/status
  verbs:
  - get
