name: main
on:
  push:
    branches: [main]
    tags: ["v*"]
    paths-ignore: ['**.md']
  pull_request:
    types: [opened, synchronize]
    paths-ignore: ['**.md']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install tools
        run: make install-tools
      - name: Install kubebuilder
        run: |
          # ref: https://book.kubebuilder.io/quick-start.html#installation
          os=$(go env GOOS)
          arch=$(go env GOARCH)

          # download kubebuilder and extract it to tmp
          curl -L https://go.kubebuilder.io/dl/2.3.1/${os}/${arch} | tar -xz -C /tmp/

          # move to a long-term location and put it on your path
          # (you'll need to set the KUBEBUILDER_ASSETS env var if you put it somewhere else)
          sudo mv /tmp/kubebuilder_2.3.1_${os}_${arch} /usr/local/kubebuilder
      # ref: https://text.superbrothers.dev/200510-ensure-go-mod-is-already-tidied-on-ci/
      - name: Ensure go.mod is already tidied
        run: go mod tidy && git diff -s --exit-code go.sum
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.38
          args: --timeout=3m0s
      - name: Run tests
        run: make test
