name: publish-image
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v3.4.0
        with:
          images: d-kuro/scheduled-pod-autoscaler
          tag-latest: false
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1.3.0
        with:
          version: latest
      - uses: docker/login-action@v1.9.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - uses: docker/build-push-action@v2.5.0
        with:
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ghcr.io/${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
