apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scheduled-pod-autoscaler-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scheduled-pod-autoscaler-leader-election-role
subjects:
- kind: ServiceAccount
  name: scheduled-pod-autoscaler
  namespace: kube-system
