apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scheduled-pod-autoscaler-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scheduled-pod-autoscaler-role
subjects:
  - kind: ServiceAccount
    name: scheduled-pod-autoscaler
    namespace: kube-system
