
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.d-kuro.github.io
  resources:
  - scheduledpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.d-kuro.github.io
  resources:
  - scheduledpodautoscalers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - autoscaling.d-kuro.github.io
  resources:
  - schedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.d-kuro.github.io
  resources:
  - schedules/status
  verbs:
  - get
  - patch
  - update
